name: CI

on: [push]

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Project Package
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
        with:
          version: "1.8.5"

      - name: Install tox
        run: pip install tox tox-gh-actions

      - name: Test
        run: poetry run tox

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout Project Package
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
      with:
        version: "1.8.5"

    - name: Install Dependencies
      run: poetry install --no-root -v

    - name: Set Python Path
      run: echo "PYTHONPATH=src" >> $GITHUB_ENV

    - name: Test
      run: poetry run pytest tests/ --cov=src/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout Project Package
      uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1
      with:
        version: "1.8.5"

    - name: Install Python Dependencies
      run: poetry install  --no-root -v

    - name: Flake8
      run: poetry run flake8 src/ tests/

    - name: Isort
      run: poetry run isort -c src/ tests/

    - name: Black
      run: poetry run black --check src/ tests/
